"""add payment request fingerprint

Revision ID: 4230f450db1f
Revises: 088a2be597ac
Create Date: 2026-08-24 12:56:26.205016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4230f450db1f'
down_revision: Union[str, Sequence[str], None] = '088a2be597ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('request_fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_payments_request_fingerprint'), 'payments', ['request_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_request_fingerprint'), table_name='payments')
    op.drop_column('payments', 'request_fingerprint')
    # ### end Alembic commands ###
