"""add transaction idempotency key

Revision ID: 9b913f4a98a8
Revises: 712b739790cd
Create Date: 2026-08-23 21:29:31.823683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b913f4a98a8'
down_revision: Union[str, Sequence[str], None] = '712b739790cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_transactions', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_ledger_transactions_idempotency_key'), 'ledger_transactions', ['idempotency_key'], unique=False)
    op.create_unique_constraint('uq_ledger_transaction_reference_type', 'ledger_transactions', ['reference_id', 'transaction_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ledger_transaction_reference_type', 'ledger_transactions', type_='unique')
    op.drop_index(op.f('ix_ledger_transactions_idempotency_key'), table_name='ledger_transactions')
    op.drop_column('ledger_transactions', 'idempotency_key')
    # ### end Alembic commands ###
